### ISSUE TITLE
Error on readonly/get properties

### ISSUE THREAD

**Issue by brinsleylogic** [sinclairzx81/typescript-bundle#12]
Hey, I'm currently having an issue where compiling any code using either the `readonly` property on a variable or the `get _functionName_` syntax.  I spent a fair bit of time commenting out various parts of my code and I've narrowed it down to this, any ideas what's up?

Code:
`public app: express.Express; // This is fine.`
`public readonly app: express.Express; // This throws an error`
`public get app(): express.Express { return this._app; } // This throws an error`

Error:
`Error: Command failed: tsc-bundle ./src/auth/main.ts --outFile ./dist/auth.js --exportAs commonjs --debug`

**Comment by sinclairzx81** [comment]
Hi,

There shouldn't be any issues with handling get/set properties using tsc-bundle and none of the code you've listed above should throw an error so not sure. Can you post the error you're seeing?

**Comment by brinsleylogic** [comment]
It looks like I might be an idiot. I've been running this as part of a gulp tasks calling `exec` on `child_process`, this stops any errors from logging out it would seem. Ran the command manually and I'm getting usable errors. Looks like it's targeting es3.

`COMMAND { commandType: 'bundle',
  outFile: 'D:\\Git\\browser-game\\dist\\auth',
  inFile: 'D:\\Git\\browser-game\\src\\auth\\main.ts',
  esTarget: undefined,
  projectRoot: 'D:\\Git\\browser-game\\src\\auth',
  inFileType: 'script',
  exportAs: 'commonjs',
  importAs: [],
  entryPoint: undefined,
  transforms: [],
  watch: false,
  debug: true,
  errorText: undefined }

TYPESCRIPT { type: 'script',
  esTarget: 'es3',
  inFile: 'D:\\Git\\browser-game\\src\\auth\\main.ts',
  outFile: 'D:\\Git\\browser-game\\dist\\auth',
  watch: false }

BUNDLER { esTarget: 'es3',
  projectRoot: 'D:\\Git\\browser-game\\src\\auth',
  importAs: [],
  exportAs: 'commonjs',
  entryPoint: undefined,
  transforms: [] }
src/server/HttpServer.ts(28,13): error TS1056: Accessors are only available when targeting ECMAScript 5 and higher.
TypeScript ended with exit code 2`

**Comment by sinclairzx81** [comment]
Ah, it happens, all good :)
