### ISSUE TITLE
Support for Runtime API to use programatically. 

### ISSUE THREAD

**Issue by seivan** [sinclairzx81/typescript-bundle#21]
Do you think there's potential to run this programmatically if we were to say export 
`bundle` & `getOptions` in `src/index.ts`?
Assuming we distribute `ts-node`and `tsc` in runtime as well? 

Edit: Would also need to add module in [`package.json`](https://github.com/sinclairzx81/typescript-bundle/blob/master/package.json)

**Comment by sinclairzx81** [comment]
@seivan Hi. Programmatic usage isn't something I've specifically focused on for this package, however I would be open to a PR that enabled it if its of any use. Should just be able to `export` the following functions https://github.com/sinclairzx81/typescript-bundle/blob/master/src/index.ts#L128-L161 and prevent the automatic `run(process.argv)` when running from CLI.

As for distributing `ts-node` and `tsc`. Would not be keen on adding `ts-node` to this package (it's kind of a separate thing) and `tsc` should be installed separately as a `peerDependency` (typescript-bundle works across all versions of typescript, so wouldn't want to mandate on a specific version). Also note, TypeScript-Bundle interacts with TypeScript via the TypeScript CLI (this is primarily to shield the library from Compiler API changes which have varied between different versions of the compiler).

**Comment by seivan** [comment]
> @seivan Hi. Programmatic usage isn't something I've specifically focused on for this package, however I would be open to a PR that enabled it if its of any use. 

If you're game, I'm up for it, will take a stab at it. 

> Should just be able to `export` the following functions https://github.com/sinclairzx81/typescript-bundle/blob/master/src/index.ts#L128-L161 and prevent the automatic `run(process.argv)` when running from CLI.

I thought I'd move those to a separate file and export them for the CLI to use. This way we can distribute a module and I don't have to worry about changes in the CLI. 


> As for distributing `ts-node` and `tsc`. Would not be keen on adding `ts-node` to this package (it's kind of a separate thing) and `tsc` should be installed separately as a `peerDependency` (typescript-bundle works across all versions of typescript, so wouldn't want to mandate on a specific version). 

Of course, wasn't saying they should be added here, just the runtime I'm planning for will supply that. 
Edit: Or initially, was planning on dynamically imported ts files in a `ts-node` runtime, but with this I can avoid that, since they got some issues with esm. 

> Also note, TypeScript-Bundle interacts with TypeScript via the TypeScript CLI (this is primarily to shield the library from Compiler API changes which have varied between different versions of the compiler).

I see, that means you're spawning child processes, correct? 
Though it sound like you might be already doing this, but if you aren't, I should perhaps validate `tsc` is in `$PATH` to run that just to keep things as they are, and only default to one under `node_modules` if it's missing.

How does this sound to you?

**Comment by sinclairzx81** [comment]
@seivan Hi, all sounds good. Would be happy to receive a PR for this project :) Just a few responses below.

> I see, that means you're spawning child processes, correct?

Yes that's right. Currently spawning `tsc` as a `child_process` (that's happening in `src/compiler/typescript.ts`). I believe `tsc-bundle` will report if it can't locate `tsc` but may need to check the logic for this (I haven't looked at this project in a while, but there should be something there to check).

> I should perhaps validate tsc is in $PATH to run that just to keep things as they are, and only default to one under node_modules if it's missing.

If running validation checks for `tsc` in the `$PATH` might be good to review this issue https://github.com/sinclairzx81/typescript-bundle/issues/13. I was planning on taking a look at this at some point but may need to resolve `tsc` from `node_modules` (resolving the path using some strategy). If you add some checks in there, just ensure its flexible to resolve from other locations.

Many Thanks!
S

**Comment by sinclairzx81** [comment]
Developing a API for this project will be challenging as this project works through the TypeScript CLI (primarily to shield it from compiler API changes from version to version). As the TypeScript compiler API has matured over the years, it may be more practical to use that directly instead wiring that functionality through TypeScript-Bundle.

Will close off this issue.
S
