### ISSUE TITLE
tsc-bundle using external modules

### ISSUE THREAD

**Issue by eyalmand1976** [sinclairzx81/typescript-bundle#24]
using tsc-bundle with external module located in node_modules causing errors that the external module was not found during run.

**Comment by sinclairzx81** [comment]
@eyalmand1976 Hi. typescript bundle does not bundle from `node_modules`, it will only bundle relative TypeScript modules you import within your project. Node module support is deemed out of scope.

If you need to bundle from node_modules, consider using `esbuild` or `webpack` (I'd highly recommend `esbuild` as it's extremely fast and light on dependencies)

Hope this helps!
