### ISSUE TITLE
the library uses require() which is not defined in browsers

### ISSUE THREAD

**Issue by ShayHaluba** [sinclairzx81/typescript-bundle#3]
Hi, maybe I am doing something wrong but when I run tsc-bundle on my main.ts, I am getting a bundle file with the following functions. which uses the require() method -

var modules = {
      "require": {
          factory: undefined,
          dependencies: [],
          exports: function (args, callback) { return **require**(args, callback); },
          resolved: true
      }
  };

function resolve(definition) {
       .
       .
       .
      var dependencies = definition.dependencies.map(function (id) {
          return (id === "exports")
              ? definition.exports
              : (function () {
                  if(modules[id] !== undefined) {
                    resolve(modules[id]);
                    return modules[id].exports;
                  } else return **require**(id)
              })();
      });
      definition.factory.apply(null, dependencies);
  }

maybe there is a way to avoid the 'require' function?

Thanks

**Comment by sinclairzx81** [comment]
Hi,

Currently, there is no mechanism to disable the fallback commonjs style require(id), but i am happy to provide an option to disable it if its causing you problems. 

The reason it exists is to allow the host to resolve dependencies external to the bundle. Basically, what happens is the loader first tries to resolve the modules from **inside** the bundle, and if not found, it attempts to call ```require(id)```, which attempts to resolve the module **external** to the bundle.

> typescript-bundle assumes the existence of this ```require()``` function, which is present in nodejs, but not inside the browser.

What this allows for is bundled nodejs modules, but also provides an injection point for providing dependencies that are not specifically part of the bundle (allowing one to write their own ```require()``` function if necessary).

I don't actively push this as a feature of the library as i haven't really had a lot of time to think about, so its cool you picked up on it. If it is causing you problems, i am happy to provide a option to either check that the ```require()``` function exists (preference), or provide switch to disable it entirely.

Thanks 
sinclair

**Comment by ShayHaluba** [comment]
Hi,

Thank you for answering so quickly,

I think you should add to the readme file that if you have a 3rd party 'import' in your project the lib will use 'require' to load it.

I guess it's not a good idea to load external libs into my bundle.js, so I am trying to think of another solution that will support my needs.
What I am actually trying to do is writing an NPM module in Typescript, and then create a single bundle.js file that I would use as a script tag in a legacy app, which doesn't support any module loaders nor typescript.

If you have any idea, I would appreciate if you share it with me.

Thanks a lot :+1:

**Comment by sinclairzx81** [comment]
Hi,

Thanks for the suggestion. I do plan to put some documentation in place around the fallback cjs ```require()```, but it does need a microscope put on it first. 

With regards to having your bundle reference external libs, this can be ok, but it depends on your needs. for example, the following would be fine in a nodejs context.

### node
```typescript
// src/app.ts
import * as http from "http" // load modules "external" to your bundle.

http.createServer((req, res) => res.end("hello"))
.listen(5000)
```
```
tsc-bundle ./src/app.ts ./bin/app.js
```
> the same would be true for importing express, or other nodejs module you might pull from npm.

### browser

For browsers tho, you have a few options. 

1) compile your external javascript dependencies in with your bundle using the ```--allowJS``` option.
2) compile your bundle as a standalone, and had a d.ts file that provides definitions for libraries your using.

```html
<script src="./jquery.js"></script> <!-- jquery must be defined first -->
<script src="./bundle.js"></script> <!-- the bundle was compiled with definitions for jquery -->
```
Knowing which approach to take really comes down to your use case and what makes the most sense in the context of your application.

From what you have described, i would probably approach things by developing your library using modules, rely on the typescript compilers multiple module targets and really put the focus on the future implementations (ones with module systems). For your legacy application, you can try and use typescript-bundle with the above options, or perhaps check out webpack which does provide a lot more elaborate options for bundling.

The goal of typescript-bundle is primarily to provide a pure typescript workflow (and to make up for the compilers lack of functionality with regards to developing javascript that is immediately consumable with a ```<script>``` tag). I would certainly be interested to hear how you get on with it. 

Oh, lastly, you may be interested, but typescript-bundle works by compiling your module as AMD + outfile, it then shims the compilers output with this file.

javascript shim
https://github.com/sinclairzx81/typescript-bundle/blob/master/src/shim.ts#L32-L74
typescript version of the shim...
https://github.com/sinclairzx81/typescript-bundle/blob/master/doc/typescript-shim.ts

So it would be possible to compile your application and manually wrap it in this shim manually if you need to. This might suit more customised bundling scenarios if you need them.

I hope this helps mate. 
cheers.
