### ISSUE TITLE
error: tsconfig is not valid json

### ISSUE THREAD

**Issue by zaaack** [sinclairzx81/typescript-bundle#4]
Official tsc can handle JSON with comments, ts-bundle should be able too.

**Comment by sinclairzx81** [comment]
Hi,

Yes, ill take a look at this in the next round of updates. 

Thanks !

**Comment by sinclairzx81** [comment]
Hi, 

I have pushed a update to allow for comments within tsconfig.json. Thanks for letting me know about this. Updates are published as of 0.8.6 on npm.

Ill leave the issue open for a week, let me know if you have any problems. 

sinclair
