### ISSUE TITLE
target option seems to be ignored

### ISSUE THREAD

**Issue by tim-we** [sinclairzx81/typescript-bundle#8]
When I build a project using `tsc-bundle src/test.ts --target es2018 --outFile dist/out.js` it does not use the intended ES target for the bundle, instead the default is used.
When building the project using `tsc-bundle tsconfig.json` (see below) the correct ES target is used.

tsconfig.json:
```json
{
  "compilerOptions": {
    "target": "es2018",      
    "outFile": "dist/game.js"
  }
}
```

**Comment by sinclairzx81** [comment]
Hi, Thanks !!

Have just pushed a patch for this issue. If you update to `typescript-bundle@1.0.13` via npm this should be resolved. 

Many Thanks
S

**Comment by sinclairzx81** [comment]
Will close off this issue, thanks for letting me know. If you run into any problems with the patch, happy to reopen and address. Thanks again. S
