### ISSUE TITLE
module isn't bundled

### ISSUE THREAD

**Issue by gbishop** [sinclairzx81/typescript-bundle#9]
I'm missing something. I've got a single typescript file 'find.ts'. Everything works fine until I import a module. I used `npm install --save stemr` to get it. I imported it into typescript with `import { stem } from "stemr";` and it compiles fine. But when I run in the browser I get Uncaught Error: module "stemr" not found.

I assumed the bundle would contain the things I imported. I bet there is some flag I need to set.

**Comment by sinclairzx81** [comment]
Hi,

Yes, TypeScript-Bundle doesn't make attempts to bundle JavaScript packages out of the NodeJS node_modules directory. It is primarily focused on being a tool for small zero dependency TypeScript projects where one would prefer to write modular typescript code (import/export syntax) but also have that code quickly bundled ready for the browser.

If you're looking to bundle packages from node_modules I would highly recommend projects like [WebPack](https://webpack.js.org/), [Rollup](https://rollupjs.org/guide/en/), [Parcel ](https://parceljs.org/) and [FuseBox ](https://fuse-box.org/) which provide more advanced bundling features.

Note: There isn't any immediate plans have TypeScript-Bundle resolve node packages in the future, but I do get asked about this enough it may be something I review down the line.

Hope this helps.
S

**Comment by gbishop** [comment]
Yes. Thanks.

**Comment by vincentrolfs** [comment]
I would love to have this feature.

**Comment by gbishop** [comment]
I've moved to snowpack. It works great for me.

**Comment by sinclairzx81** [comment]
@gbishop @vincentrolfs Hi, Unfortunately, this project isn't actively maintained anymore. I may mark it as `readonly` in future. TypeScript-Bundle was written a long time ago to smooth over TypeScript not having a direct bundling option available in the compiler. It was never really intended to go the full way to provide bundling for dependencies out of `node_modules` as seen in systems like WebPack, Rollup, Parcel, etc. (but have had a lot of requests for that over the years).

This said, I have actually moved on from this project and written https://github.com/sinclairzx81/hammer as a direct successor to TypeScript-Bundle. It does everything TypeScript-Bundle does (as well as dependency bundling from `node_modules` as requested in this issue), but also supports bundling JavaScript, CSS and HTML. It's designed to function similar to TypeScript-Bundle but is actually an amalgamation of several other tools I've written over the years relating to project automation and workflow. Hammer is primarily where my efforts are directed these days.

I may update this project with the ES2020 compiler target when I get a bit of free time, followed by a final deprecation notice. I hope you have gotten some reasonable mileage from this project however. 

Cheers
S
